name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you have linting tools, you can install them here:
          # pip install flake8 black

      # 4. Linting (Optional)
      - name: Lint with flake8
        run: |
          # If flake8 is installed in your requirements.txt or installed above
          flake8 src tests

      # 5. Run tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings

      # 6. Deployment (Placeholder)
      - name: Deploy stage
        run: |
          echo "Deployment step goes here (e.g. Docker build/push, or cloud deploy)."
