name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies and save virtual environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8 pytest
      - name: Save workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run lint
        run: |
          flake8 src tests

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest --maxfail=1 --disable-warnings

  deploy:
    needs: 
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
      - name: deploy
        run: |
          echo "Deploying model..."
